apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
patchesStrategicMerge:
  - repo.yaml
resources:
  - namespace.yaml
  - "https://raw.githubusercontent.com/argoproj/argo-cd/v1.7.10/manifests/install.yaml"
  - secret.yaml
  - projects/default.yaml
  - bootstrap.yaml
