apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "sample01"
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/kaito2/locust-on-gke.git
    targetRevision: HEAD
    path: apps/sample01
  destination:
    server: https://kubernetes.default.svc
    namespace: "sample01"
